### ISSUE TITLE
大佬，请问下修复extract oxts测量值的timestamp异常的步骤问题

### ISSUE THREAD

**Issue by q87956256** [AlexGeControl/Sensor-Fusion#1]
大佬，想请教下，您的修复extract oxts测量值的timestamp异常. 原始timestamp差分的统计描述如下...
这一步修复时间戳的操作中， 这个generate_100hz_oxts.py怎么用啊？是不是要将sync的那个同步的sync中的oxts文件夹名字改成oxts_sync，同时将extract中的oxts文件夹改成oxts_extract文件夹，然后将这两个文件夹放在同一个目录下，然后运行generate_100hz_oxts.py ，-i 输入这两个文件夹的路径 ，就行了？我运行的结果是这样：
count                     45833
mean     0 days 00:00:00.010288
std      0 days 00:00:00.005598
min             0 days 00:00:00
25%      0 days 00:00:00.009967
50%      0 days 00:00:00.009996
75%      0 days 00:00:00.010025
max      0 days 00:00:00.519616
Name: timestamp, dtype: object
不知道我这个结果是OK的吗？ 然后将新生成的oxts替换掉原来2011_10_03_drive_0027_sync目录中的oxts，再用您的那个修改好的kitti2bag 生成bag就行了对吧？ 我不懂python.....

**Comment by AlexGeControl** [comment]
流程已经在README更新了, 另外这个工作, 严格意义上还属于需要独立完成的作业

**Comment by q87956256** [comment]
谢谢大佬了，主要是不懂python，而且工作比较忙，想把主要精力集中在老师的核心问题上。。。。

**Comment by AlexGeControl** [comment]
ESKF实现仅仅是20%的工作, 剩下80%和机器学习炼丹一样, 都要耗在数据处理上
