### ISSUE TITLE
算法推导的链接打不开

### ISSUE THREAD

**Issue by lucianzhong** [AlexGeControl/Sensor-Fusion#2]
博主您好：
在 04-imu-lidar-gnss-fusion这个里面，算法推导的链接打不开，“算法的理论推导以及针对KITTI Road Test Data的伪代码实现参考 here”，”组合导航(GNSS + IMU)的滤波模型参考 here“
看您那边是否方面可以修复一下，非常感谢。

**Comment by AlexGeControl** [comment]
第一个已删除, 不打算提供. 请直接参考代码实现.
第二个已添加
